language: node_js
node_js:
  - "8"
script:
  - echo "Deploying!"
install:
  - npm install -g firebase-tools
  - npm ci
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master
